import os
import requests


def sign_in():
    """
        Signs into breezy using account credentials
    :param:
    :return:
    """
    user_mail = os.environ["BREEZY_USER"]
    password = os.environ["BREEZY_PASS"]

    my_session = requests.session()
    sign_in_url = "https://app.breezy.hr/signin"
    data = {
        "email_address": user_mail,
        "password": password
    }
    headers = {
        "content-type": "application/x-www-form-urlencoded"
    }
    my_session.post(url=sign_in_url, data=data, headers=headers)
    return my_session


def download_file(file_url_breezy):
    """
        Downloads a file from breezy.hr by signing in to account
    :param file_url_breezy: URL of the file to be downloaded
    :return:
    """
    my_session = sign_in()
    doc_file_name = str(file_url_breezy).split("/")[-1]
    y = my_session.get(url=str(file_url_breezy))
    if y.status_code == 401:
        return ["Unauthorised", False]
    elif y.status_code != 200:
        return ["Unknown Error", False]
    if os.path.exists(os.path.join("helpers", "resumes")):
        pass
    else:
        os.mkdir(os.path.join("helpers", "resumes"))
    save_file_path = os.path.join("helpers", "resumes", doc_file_name)
    pdf = open(save_file_path, 'wb')
    pdf.write(y.content)
    pdf.close()
    return [doc_file_name, True]


def download_file_single_session(my_session, file_url_breezy):
    """
        Downloads a file from breezy.hr using an existing session
    :param my_session: request session which stores the cookies generated by signing in
    :param file_url_breezy: URL of the file to be downloaded
    :return:
    """
    doc_file_name = str(file_url_breezy).split("/")[-1]
    y = my_session.get(url=file_url_breezy)
    if y.status_code == 401:
        return ["Unauthorised", False]
    elif y.status_code != 200:
        return ["Unknown Error", False]
    if os.path.exists("resumes"):
        pass
    else:
        os.mkdir("resumes")
    save_file_path = os.path.join("resumes", doc_file_name)
    pdf = open(save_file_path, 'wb')
    pdf.write(y.content)
    pdf.close()
    return [doc_file_name, True]

